# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 96c5d63a8c22af12711330b21a4466e26a9e2c51386ad1b53fd639d2abcfe5666650815c4c5198375fe2b02db0e93f4c59c1e55aef33a9a2364c8248748be587

test:
  secret_key_base: cd3e680170df7792912cf176592f2947cd56961c6eb1625a763c4c34a99f49c8e8f51d878e0c2ea1c4039514b4b4eb980e0d6b984043df2f3520f05ec0915cef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
